openapi: 3.0.0
info:
  title: Blogsome
  description: OpenApi spec for Blogsome
  contact:
    name: Tshegofatso Manthata
    email: tshegofatsomanthata@gmail.com
  version: "1.0"
servers:
  - url: http://localhost:8080/api/v1
paths:



